import path from "path";
import { PlannedFile } from "../../io/file-writer";
import { createNameVariants } from "../../templates/naming";

export interface AddControllerPlan {
  name: string;
  feature: string;
  featuresRoot: string;
  path?: string;
}

export function createControllerFile(plan: AddControllerPlan): PlannedFile {
  const controllerNames = createNameVariants(plan.name);
  const featureNames = createNameVariants(plan.feature);
  const basePath = normalizeControllerPath(plan.path ?? `/${controllerNames.kebabName}`);

  return {
    path: path.posix.join(
      plan.featuresRoot,
      featureNames.kebabName,
      "api",
      `${controllerNames.kebabName}.controller.ts`
    ),
    type: "controller",
    owner: featureNames.kebabName,
    content: createControllerTs(controllerNames.pascalName, controllerNames.kebabName, basePath),
  };
}

function createControllerTs(className: string, kebabName: string, basePath: string): string {
  return `import { Controller, Delete, Get, Post, Put } from '@soapjs/soap-express';

@Controller('${basePath}', {
  apiDoc: {
    tags: ['${className}'],
    description: '${className} mock controller generated by SoapJS CLI',
  },
})
export class ${className}Controller {
  // @Get('/', {
  //   apiDoc: {
  //     summary: 'List ${kebabName}',
  //     operationId: 'list${className}',
  //     responses: { '200': { description: 'Success' } },
  //   },
  // })
  // async list(): Promise<unknown> {
  //   return { items: [] };
  // }

  // @Get('/:id', {
  //   apiDoc: {
  //     summary: 'Get ${kebabName}',
  //     operationId: 'get${className}',
  //     responses: { '200': { description: 'Success' } },
  //   },
  // })
  // async get(req: { params: { id: string } }): Promise<unknown> {
  //   return { id: req.params.id };
  // }

  // @Post('/', {
  //   apiDoc: {
  //     summary: 'Create ${kebabName}',
  //     operationId: 'create${className}',
  //     responses: { '200': { description: 'Success' } },
  //   },
  // })
  // async create(req: { body: unknown }): Promise<unknown> {
  //   return req.body;
  // }

  // @Put('/:id', {
  //   apiDoc: {
  //     summary: 'Update ${kebabName}',
  //     operationId: 'update${className}',
  //     responses: { '200': { description: 'Success' } },
  //   },
  // })
  // async update(req: { params: { id: string }; body: Record<string, unknown> }): Promise<unknown> {
  //   return { id: req.params.id, ...req.body };
  // }

  // @Delete('/:id', {
  //   apiDoc: {
  //     summary: 'Delete ${kebabName}',
  //     operationId: 'delete${className}',
  //     responses: { '200': { description: 'Success' } },
  //   },
  // })
  // async delete(req: { params: { id: string } }): Promise<unknown> {
  //   return { id: req.params.id, deleted: true };
  // }
}
`;
}

function normalizeControllerPath(value: string): string {
  const normalized = value.replace(/\/+/g, "/");
  return normalized.startsWith("/") ? normalized : `/${normalized}`;
}
